### ISSUE TITLE
Surah names not in mushaf.txt

### ISSUE THREAD

**Issue by agmemon10** [alquran-foundation/qpc-fonts#1]
Does anyone have the characters that represent the surah names that are to be used with the QCF_BSML.TTF font (see picture for example with Surah al-Mulk)? I did not see these characters in the mushaf.txt file

![image](https://user-images.githubusercontent.com/24301739/74580349-2fcbb700-4f71-11ea-8f13-962092837850.png)

**Comment by mustafa0x** [comment]
`\uFB8D` for "سورة".

And this function for the rest:

```js
const get_surah_char = i => String.fromCharCode(i + 64396 + (i > 37 ? 33 : 0));
```

**Comment by agmemon10** [comment]
JazakAllahu khayran! You're a genius! Just fyi, i think \ufb8c is what gives "سورة" and \ufb8d is for "الفاتحة"

And it just might be an issue specific to me, and not sure why, but for some reason, some surah names seem more **bold** than others

**Comment by mustafa0x** [comment]
Ah, yes, indeed. One off.
